-- ######################################################################
-- # SCHEMA ATUALIZADO (MAIO 2026)
-- # Base de Dados: Finanças Inteligentes
-- ######################################################################

-- 1. Tabela de Utilizadores
create table public.users (
  id bigint generated by default as identity not null,
  external_id text not null,
  provider text not null,
  display_name text not null,
  email text not null,
  created_at timestamp with time zone not null default now(),
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email),
  constraint users_external_id_provider_key unique (external_id, provider)
) TABLESPACE pg_default;

-- 2. Tabela de Subscrições
create table public.subscriptions (
  id bigserial not null,
  user_id text not null,
  name text not null,
  amount numeric(12, 2) not null,
  billing_day smallint not null,
  category text null default 'Serviços'::text,
  is_active boolean null default true,
  color text null default '#3B82F6'::text,
  created_at timestamp with time zone null default now(),
  constraint subscriptions_pkey primary key (id)
) TABLESPACE pg_default;

-- 3. Objetivos de Poupança
create table public.savings_goals (
  id integer generated by default as identity not null,
  user_id bigint not null,
  name text not null,
  target_amount numeric not null,
  current_amount numeric not null default 0,
  deadline date null,
  constraint savings_goals_pkey primary key (id),
  constraint savings_goals_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE,
  constraint target_amount_must_be_positive check ((target_amount > (0)::numeric))
) TABLESPACE pg_default;

-- 4. Investimentos (Stocks & Crypto)
create table public.investments (
  id integer generated by default as identity not null,
  user_id bigint not null,
  symbol text not null,
  market public.market_type not null, -- Requer definição prévia do TYPE market_type
  quantity numeric not null default 0,
  avg_price numeric null,
  last_price numeric null,
  currency character(3) not null,
  constraint investments_pkey primary key (id),
  constraint investments_user_id_symbol_key unique (user_id, symbol),
  constraint investments_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

-- 5. Categorias Personalizadas
create table public.categories (
  id integer generated by default as identity not null,
  user_id bigint null,
  name text not null,
  colour text null,
  constraint categories_pkey primary key (id),
  constraint categories_name_user_id_key unique (name, user_id),
  constraint categories_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

-- 6. Orçamentos (Budgets)
create table public.budgets (
  id integer generated by default as identity not null,
  user_id bigint not null,
  name text not null,
  amount numeric not null,
  period public.budget_period_type not null, -- Requer definição prévia do TYPE budget_period_type
  start_date date null,
  end_date date null,
  constraint budgets_pkey primary key (id),
  constraint budgets_name_user_id_key unique (name, user_id),
  constraint budgets_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE,
  constraint amount_must_be_non_negative check ((amount >= (0)::numeric))
) TABLESPACE pg_default;

create table public.expenses (
  id integer generated by default as identity not null,
  user_id bigint not null,
  type public.transaction_type not null,
  amount numeric not null,
  currency character(3) not null,
  category_id integer null,
  date date not null,
  notes text null,
  created_at timestamp with time zone not null default now(),
  constraint expenses_pkey primary key (id),
  constraint expenses_category_id_fkey foreign KEY (category_id) references categories (id) on delete set null,
  constraint expenses_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE,
  constraint amount_must_be_positive check ((amount > (0)::numeric))
) TABLESPACE pg_default;