-- ######################################################################
-- # SCRIPT DE CRIAÇÃO DA BASE DE DADOS - FINANÇAS INTELIGENTES (SUPABASE/POSTGRESQL)
-- #
-- # Este script cria todos os tipos ENUM e as 8 tabelas do esquema,
-- # garantindo a ordem correta para a criação das Chaves Estrangeiras (FK).
-- ######################################################################

-- # 1. CRIAÇÃO DOS TIPOS ENUM PERSONALIZADOS
----------------------------------------------------------------------

-- Tipo para a tabela 'expenses' (Despesas/Receitas)
CREATE TYPE transaction_type AS ENUM ('expense', 'income');

-- Tipo para a tabela 'budgets' (Periodicidade do Orçamento)
CREATE TYPE budget_period_type AS ENUM ('monthly', 'yearly', 'custom');

-- Tipo para a tabela 'investments' (Mercado de Ativo)
CREATE TYPE market_type AS ENUM ('stock', 'crypto');

-- Tipo para a tabela 'investment_tx' (Tipo de Transação de Investimento)
CREATE TYPE transaction_investment_type AS ENUM ('buy', 'sell');


-- # 2. CRIAÇÃO DAS TABELAS (A ORDEM DEVE SER RESPEITADA DEVIDO ÀS CHAVES ESTRANGEIRAS)
----------------------------------------------------------------------

-- 2.1. TABELA 'users' (Não depende de nenhuma outra)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    display_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- Restrição de Unicidade Combinada (OAuth)
    UNIQUE (external_id, provider)
);
COMMENT ON TABLE users IS 'Tabela de utilizadores, ligada a provedores OAuth.';


-- 2.2. TABELA 'categories' (FK para users.id)
CREATE TABLE categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    colour TEXT NULL,

    -- Restrição de Unicidade Combinada (Nome por utilizador)
    UNIQUE (name, user_id)
);
COMMENT ON TABLE categories IS 'Tabela de categorias definidas pelos utilizadores ou globais.';


-- 2.3. TABELA 'expenses' (FK para users.id e categories.id)
CREATE TABLE expenses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type transaction_type NOT NULL,
    amount NUMERIC NOT NULL,
    currency CHAR(3) NOT NULL,
    category_id INT REFERENCES categories(id) ON DELETE SET NULL,
    date DATE NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- Restrição: Valor da transação deve ser positivo
    CONSTRAINT amount_must_be_positive CHECK (amount > 0)
);
COMMENT ON TABLE expenses IS 'Tabela de registo de despesas e receitas dos utilizadores.';


-- 2.4. TABELA 'budgets' (FK para users.id)
CREATE TABLE budgets (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    period budget_period_type NOT NULL,
    start_date DATE,
    end_date DATE,

    -- Restrição de Unicidade Combinada (Nome por utilizador)
    UNIQUE (name, user_id),
    -- Restrição: Valor planeado deve ser não-negativo
    CONSTRAINT budget_amount_must_be_non_negative CHECK (amount >= 0)
);
COMMENT ON TABLE budgets IS 'Tabela de orçamentos planeados pelos utilizadores.';


-- 2.5. TABELA 'savings_goals' (FK para users.id)
CREATE TABLE savings_goals (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    target_amount NUMERIC NOT NULL,
    current_amount NUMERIC NOT NULL DEFAULT 0,
    deadline DATE,

    -- Restrição: Meta deve ser maior que zero
    CONSTRAINT target_amount_must_be_positive CHECK (target_amount > 0)
);
COMMENT ON TABLE savings_goals IS 'Tabela de objetivos de poupança definidos pelos utilizadores.';


-- 2.6. TABELA 'investments' (FK para users.id)
CREATE TABLE investments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    symbol TEXT NOT NULL,
    market market_type NOT NULL,
    quantity NUMERIC NOT NULL DEFAULT 0,
    avg_price NUMERIC NULL,
    last_price NUMERIC NULL,
    currency CHAR(3) NOT NULL,

    -- Restrição de Unicidade Combinada (Símbolo por utilizador)
    UNIQUE (user_id, symbol)
);
COMMENT ON TABLE investments IS 'Tabela de ativos de investimento (ações, cripto, etc.) detidos pelos utilizadores.';


-- 2.7. TABELA 'investment_tx' (FK para investments.id)
CREATE TABLE investment_tx (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investment_id INT NOT NULL REFERENCES investments(id) ON DELETE CASCADE,
    type transaction_investment_type NOT NULL,
    quantity NUMERIC NOT NULL,
    price NUMERIC NOT NULL,
    date DATE NOT NULL,

    -- Restrições: Quantidade e preço devem ser positivos
    CONSTRAINT tx_quantity_must_be_positive CHECK (quantity > 0),
    CONSTRAINT tx_price_must_be_positive CHECK (price > 0)
);
COMMENT ON TABLE investment_tx IS 'Regista transações individuais de compra e venda para um ativo de investimento.';


-- 2.8. TABELA 'notifications' (FK para users.id)
CREATE TABLE notifications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    payload JSONB NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE notifications IS 'Armazena notificações e alertas destinados a utilizadores específicos.';